/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelview.QLHoaDon_PhuPhi;
import service.IHoaDon_PhuPhiService;
import service.Impl.HoaDonPhuPhiServiceImpl;

/**
 *
 * @author Admin
 */
public class FrmChiTietPhuPhi extends javax.swing.JFrame {

    private String idHoaDon;
    private FrmThanhToan frmThanhToan;
    private DefaultTableModel dtm = new DefaultTableModel();
    private List<QLHoaDon_PhuPhi> listHDPP = new ArrayList<>();
    private IHoaDon_PhuPhiService don_PhuPhiService = new HoaDonPhuPhiServiceImpl();

    /**
     * Creates new form FrmChiTietPhuPhi
     */
    public FrmChiTietPhuPhi(String id, FrmThanhToan frmThanhToan) {
        initComponents();
        jTable1.setModel(dtm);
        this.frmThanhToan = frmThanhToan;
        this.idHoaDon = id;
        String headers[] = {"Mã PP", "Tên Phụ Phí", "Giá Phụ Phí"};
        listHDPP = don_PhuPhiService.getAllPhuPhi_HoaDonsByIdHoaDon(idHoaDon);
        dtm.setColumnIdentifiers(headers);
        addToRow(listHDPP);
        this.setLocationRelativeTo(null);
    }

    public void addToRow(List<QLHoaDon_PhuPhi> listHDPP) {
        dtm.setRowCount(0);
        for (QLHoaDon_PhuPhi qLHoaDon_PhuPhi : listHDPP) {
            Object[] obj = new Object[]{qLHoaDon_PhuPhi.getPhuPhi().getMaPhuPhi(), qLHoaDon_PhuPhi.getPhuPhi().getTenPhuPhi(), qLHoaDon_PhuPhi.getGiaPPHD()};
            dtm.addRow(obj);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpopChiTietPP = new javax.swing.JPopupMenu();
        jMenuXoaPP = new javax.swing.JMenuItem();
        jMenuSuaGiaPP = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jMenuXoaPP.setText("Xóa Phụ Phí");
        jMenuXoaPP.setToolTipText("");
        jMenuXoaPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuXoaPPActionPerformed(evt);
            }
        });
        jpopChiTietPP.add(jMenuXoaPP);

        jMenuSuaGiaPP.setText("Sửa Giá Phụ Phí");
        jMenuSuaGiaPP.setToolTipText("");
        jMenuSuaGiaPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSuaGiaPPActionPerformed(evt);
            }
        });
        jpopChiTietPP.add(jMenuSuaGiaPP);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Chi Tiết Phụ Phí");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(153, 153, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuXoaPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuXoaPPActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(rootPane, "Xác Nhận Xóa !!");
        if (i == 0) {
            if (don_PhuPhiService.delete(listHDPP.get(jTable1.getSelectedRow()).getId())) {
                JOptionPane.showMessageDialog(rootPane, "Xoa Thanh Cong");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Xoa That Bai");
            }
            frmThanhToan.setTxtGia();
        }
    }//GEN-LAST:event_jMenuXoaPPActionPerformed

    private void jMenuSuaGiaPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSuaGiaPPActionPerformed
        // TODO add your handling code here:
        QLHoaDon_PhuPhi qLHoaDon_PhuPhi = listHDPP.get(jTable1.getSelectedRow());
        String soLuong = JOptionPane.showInputDialog(rootPane, "Mời Nhập Số Lượng Dịch Vụ !!");
        if (soLuong == null) {
            return;
        } else {
            if (soLuong.isEmpty() || !soLuong.matches("-?\\d+(\\.\\d+)?")) {
                JOptionPane.showMessageDialog(rootPane, "Vui Long Nhập Số");
            } else {
                qLHoaDon_PhuPhi.setGiaPPHD(Double.valueOf(soLuong));
                don_PhuPhiService.update(qLHoaDon_PhuPhi);
            }
        }
        addToRow(listHDPP);
        frmThanhToan.setTxtGia();
    }//GEN-LAST:event_jMenuSuaGiaPPActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() >= 0) {
            if (evt.isPopupTrigger()) {
                jpopChiTietPP.show(jScrollPane1, evt.getPoint().x, evt.getPoint().y);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Xin Mời Chọn!!!");
        }
        addToRow(listHDPP);
        frmThanhToan.setTxtGia();
    }//GEN-LAST:event_jTable1MouseReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuSuaGiaPP;
    private javax.swing.JMenuItem jMenuXoaPP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPopupMenu jpopChiTietPP;
    // End of variables declaration//GEN-END:variables
}
