/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import domainmodel.Acount;
import domainmodel.KhachHang;
import domainmodel.SanCa;
import enumclass.trangThaiKhachHang;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelview.QLAcount;
import modelview.QLKhachHang;
import modelview.QLSanCa;
import service.IKhachHangService;
import service.Impl.KhachHangServiceImpl;

/**
 *
 * @author hp
 */
public class FrmKhachHang extends javax.swing.JFrame {

    private List<QLKhachHang> listKhachHang = new ArrayList<>();
    private IKhachHangService iKhachHangService = new KhachHangServiceImpl();
    private DefaultTableModel dtm = new DefaultTableModel();
    private QLSanCa sanCa = new QLSanCa();
    private Acount acount = new Acount();
    private JLabel labelHome;
    private JPanel pnTong;
    private Date ngayTao = new Date();

    /**
     * Creates new form FrmKhachHang
     */
    public FrmKhachHang(QLSanCa sanCa, Acount acountEntity, JLabel labHome, JPanel pnTong, Date ngayTao) {
        initComponents();
        bg.setBackground(new Color(186, 228, 229));
        this.ngayTao = ngayTao;
        this.labelHome = labHome;
        this.pnTong = pnTong;
        acount = acountEntity;
        this.sanCa = sanCa;
        jTable1.setModel(dtm);
        String[] header = {"Mã KH", "Tên KH", "Email", "SÐT", "Ghi Chú", "Trạng thái"};
        dtm.setColumnIdentifiers(header);
        listKhachHang = iKhachHangService.getAll();
        txtMaKH.disable();
        showData(listKhachHang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        radioCanhBao = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        radioBinhThuong = new javax.swing.JRadioButton();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtTenKh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSoDT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setUndecorated(true);

        buttonGroup1.add(radioCanhBao);
        radioCanhBao.setText("Cảnh cáo");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Search");

        buttonGroup1.add(radioBinhThuong);
        radioBinhThuong.setText("Bình thường");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã khách hàng");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Khách Hàng");

        jLabel2.setText("Tên khách hàng");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel3.setText("SĐT");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel4.setText("Ghi chú");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel5.setText("Trạng thái");

        jLabel6.setText("Email");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel8))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(radioCanhBao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBinhThuong))
                            .addComponent(txtEmail)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtSoDT)
                            .addComponent(txtTenKh)
                            .addComponent(txtMaKH)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnSave)
                .addGap(62, 62, 62)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(62, 62, 62)
                .addComponent(jButton1)
                .addGap(56, 56, 56))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenKh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(radioCanhBao)
                    .addComponent(radioBinhThuong))
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)))
                .addGap(35, 35, 35)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String id = UUID.randomUUID().toString();
        String ten = txtTenKh.getText().trim();
        String ma = txtMaKH.getText().trim();
        String ghiChu = txtGhiChu.getText().trim();
        String sdt = txtSoDT.getText().trim();
        String email = txtEmail.getText().trim();
        QLKhachHang qLKhachHang = new QLKhachHang();
        if (radioBinhThuong.isSelected()) {
            qLKhachHang.setTrangThai(trangThaiKhachHang.BINH_THUONG);
        } else {
            qLKhachHang.setTrangThai(trangThaiKhachHang.CANH_CAO);
        }

        if (ten.length() == 0 || sdt.length() == 0 || email.length() == 0) {
            JOptionPane.showMessageDialog(this, "Null");
        } else if (!sdt.matches("^0\\d{9}$")) {
            JOptionPane.showMessageDialog(this, "SDT Sai dinh dang");

        } else if (!email.matches("^(.+)@(.+)$")) {
            JOptionPane.showMessageDialog(this, "Email Sai dinh dang");
        } else {
            KhachHang khachHang = new KhachHang(id, iKhachHangService.genMaKH(), ten, email, sdt, ghiChu, qLKhachHang.getTrangThai());
            String checkSave = iKhachHangService.save(khachHang);

            listKhachHang = iKhachHangService.getAll();
            showData(listKhachHang);
            if (checkSave.equals("Save complete")) {
                int check = JOptionPane.showConfirmDialog(rootPane, "Xác nhận thêm khách hàng", "Thông Báo", JOptionPane.YES_NO_OPTION);
                if (check == JOptionPane.YES_OPTION) {
                    QLKhachHang qLKhachHang1 = new QLKhachHang(khachHang.getId(), iKhachHangService.genMaKH(), khachHang.getTenKhachHang(),
                            khachHang.getMail(), khachHang.getSoDienThoai(), khachHang.getGhiChu(), khachHang.getTrangThai());
                    new FrmPhieuDatLich(qLKhachHang1, sanCa, acount, labelHome, pnTong, ngayTao).setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Lưu thất bại");
            }
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = jTable1.getSelectedRow();
        String ten = txtTenKh.getText().trim();
        String ma = txtMaKH.getText().trim();
        String ghiChu = txtGhiChu.getText().trim();
        String sdt = txtSoDT.getText().trim();
        String email = txtEmail.getText().trim();
        QLKhachHang qLKhachHang = new QLKhachHang();
        if (radioBinhThuong.isSelected()) {
            qLKhachHang.setTrangThai(trangThaiKhachHang.BINH_THUONG);
        } else {
            qLKhachHang.setTrangThai(trangThaiKhachHang.CANH_CAO);
        }
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selected row ??");
        } else {
            if (ten.length() == 0 || sdt.length() == 0 || email.length() == 0) {
                JOptionPane.showMessageDialog(this, "Null");
            } else if (!sdt.matches("^0\\d{9}$")) {
                JOptionPane.showMessageDialog(this, "SDT Sai dinh dang");

            } else if (!email.matches("^(.+)@(.+)$")) {
                JOptionPane.showMessageDialog(this, "Email Sai dinh dang");
            } else {
                QLKhachHang khachHang = new QLKhachHang(mountClick().getId(), iKhachHangService.genMaKH(), ten, email, sdt, ghiChu, qLKhachHang.getTrangThai());
                JOptionPane.showMessageDialog(this, iKhachHangService.update(khachHang));
                listKhachHang = iKhachHangService.getAll();
                showData(listKhachHang);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = jTable1.getSelectedRow();
        String ten = txtTenKh.getText().trim();
        String ma = txtMaKH.getText().trim();
        String ghiChu = txtGhiChu.getText().trim();
        String sdt = txtSoDT.getText().trim();
        String email = txtEmail.getText().trim();
        QLKhachHang qLKhachHang = new QLKhachHang();
        if (radioBinhThuong.isSelected()) {
            qLKhachHang.setTrangThai(trangThaiKhachHang.BINH_THUONG);
        } else {
            qLKhachHang.setTrangThai(trangThaiKhachHang.CANH_CAO);
        }
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selected row ??");
        } else {
            QLKhachHang khachHang = new QLKhachHang(mountClick().getId(), iKhachHangService.genMaKH(), ten, email, sdt, ghiChu, qLKhachHang.getTrangThai());
            JOptionPane.showMessageDialog(this, iKhachHangService.delete(khachHang));
            listKhachHang = iKhachHangService.getAll();
            showData(listKhachHang);

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int check = JOptionPane.showConfirmDialog(rootPane, "Xác nhận thêm khách hàng", "Thông Báo", JOptionPane.YES_NO_OPTION);
        int index = jTable1.getSelectedRow();
        fillData(index);
        QLKhachHang qLKhachHang = listKhachHang.get(index);
        if (check == JOptionPane.YES_OPTION) {
            new FrmPhieuDatLich(qLKhachHang, sanCa, acount, labelHome, pnTong, ngayTao).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        listKhachHang.clear();
        listKhachHang = iKhachHangService.searchByName(txtSearch.getText());
        showData(listKhachHang);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        QLKhachHang qLKhachHang = new QLKhachHang();
        new FrmPhieuDatLich(qLKhachHang, sanCa, acount, labelHome, pnTong, ngayTao).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private QLKhachHang mountClick() {
        int row = jTable1.getSelectedRow();
        return listKhachHang.get(row);
    }

    private void fillData(int index) {
        QLKhachHang qLKhachHang = listKhachHang.get(index);
        txtGhiChu.setText(qLKhachHang.getGhiChu());
        txtMaKH.setText(qLKhachHang.getMaKhachHang());
        txtSoDT.setText(qLKhachHang.getSoDienThoai());
        txtTenKh.setText(qLKhachHang.getTenKhachHang());
        txtEmail.setText(qLKhachHang.getMail());
        if (qLKhachHang.getTrangThai() == trangThaiKhachHang.BINH_THUONG) {
            radioBinhThuong.setSelected(true);
        } else {
            radioCanhBao.setSelected(true);

        }
    }

    private void showData(List<QLKhachHang> listQLKhachHang) {
        dtm.setRowCount(0);
        for (QLKhachHang qLKhachHang : listQLKhachHang) {
            dtm.addRow((Object[]) qLKhachHang.toDataRow());
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton radioBinhThuong;
    private javax.swing.JRadioButton radioCanhBao;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JTextField txtTenKh;
    // End of variables declaration//GEN-END:variables
}
