/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controller.HomeController;
import domainModel.GiaoCa;
import domainmodel.Acount;
import enumclass.trangThaiGiaoCa;
import java.awt.Color;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import modelview.QLAcount;
import service.IGiaoCaService;
import service.Impl.GiaoCaServiceImpl;
import utill.MaRanDom;

/**
 *
 * @author DANG VAN SY
 */
public class JpnKhaiBaoTienDauCa extends javax.swing.JPanel {

    private QLAcount qLAcount;
    private IGiaoCaService giaoCaService = new GiaoCaServiceImpl();
    private JPanel pnTOng;
    private JLabel lableHome;

    public JpnKhaiBaoTienDauCa(QLAcount qLAcount, JPanel pnTOng, JLabel lableHome) {
        initComponents();
        this.qLAcount = qLAcount;
        this.lableHome = lableHome;
        this.pnTOng = pnTOng;
        lbMenhGia.setBackground(new Color(160, 132, 157));
        labelSoLuong.setBackground(new Color(160, 132, 157));
        labelThanhTien.setBackground(new Color(160, 132, 157));
        lbTenNv.setText(qLAcount.getTenAcount());
        lbGioVaoCa.setText(new SimpleDateFormat("dd/MM/yyyy - hh:mm:ss a").format(gioNhanCa()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTong = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelThanhTien = new javax.swing.JLabel();
        labelSoLuong = new javax.swing.JLabel();
        lbMenhGia = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt500 = new javax.swing.JTextField();
        txt200 = new javax.swing.JTextField();
        txt100 = new javax.swing.JTextField();
        txt50 = new javax.swing.JTextField();
        txt20 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        lbTT500 = new javax.swing.JLabel();
        lbTT200 = new javax.swing.JLabel();
        lbTT100 = new javax.swing.JLabel();
        lbTT50 = new javax.swing.JLabel();
        lbTT20 = new javax.swing.JLabel();
        lbTT10 = new javax.swing.JLabel();
        lbTT5 = new javax.swing.JLabel();
        lbTT2 = new javax.swing.JLabel();
        lbTT1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        lbNhanCa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbTenNv = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbGioVaoCa = new javax.swing.JLabel();

        panelTong.setBackground(new java.awt.Color(65, 147, 169));

        jPanel2.setBackground(new java.awt.Color(11, 127, 171));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelThanhTien.setBackground(new java.awt.Color(0, 153, 51));
        labelThanhTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelThanhTien.setText("Thành tiền");
        labelThanhTien.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelSoLuong.setBackground(new java.awt.Color(0, 153, 51));
        labelSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSoLuong.setText("Số lượng");
        labelSoLuong.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbMenhGia.setBackground(new java.awt.Color(0, 153, 51));
        lbMenhGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenhGia.setText("Mệnh giá");
        lbMenhGia.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("500.000 Vnd");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("200.000 Vnd ");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("100.000 Vnd");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("50.000 Vnd");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("20.000 Vnd");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("10.000 Vnd");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("5.000 Vnd");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("2.000 Vnd");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("1.000 Vnd");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt500.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt500.setText("0");
        txt500.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt500KeyTyped(evt);
            }
        });

        txt200.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt200.setText("0");
        txt200.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt200KeyTyped(evt);
            }
        });

        txt100.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt100.setText("0");
        txt100.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt100KeyTyped(evt);
            }
        });

        txt50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt50.setText("0");
        txt50.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt50KeyTyped(evt);
            }
        });

        txt20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt20.setText("0");
        txt20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt20KeyTyped(evt);
            }
        });

        txt10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt10.setText("0");
        txt10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt10KeyTyped(evt);
            }
        });

        txt5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt5.setText("0");
        txt5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt5KeyTyped(evt);
            }
        });

        txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2.setText("0");
        txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt2KeyTyped(evt);
            }
        });

        txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1.setText("0");
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt1KeyTyped(evt);
            }
        });

        lbTT500.setForeground(new java.awt.Color(255, 0, 0));
        lbTT500.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTT500.setText("0");
        lbTT500.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTT200.setForeground(new java.awt.Color(255, 0, 0));
        lbTT200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTT200.setText("0");
        lbTT200.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTT100.setForeground(new java.awt.Color(255, 0, 0));
        lbTT100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTT100.setText("0");
        lbTT100.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTT50.setForeground(new java.awt.Color(255, 0, 0));
        lbTT50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTT50.setText("0");
        lbTT50.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTT20.setForeground(new java.awt.Color(255, 0, 0));
        lbTT20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTT20.setText("0");
        lbTT20.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTT10.setForeground(new java.awt.Color(255, 0, 0));
        lbTT10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTT10.setText("0");
        lbTT10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTT5.setForeground(new java.awt.Color(255, 0, 0));
        lbTT5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTT5.setText("0");
        lbTT5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTT2.setForeground(new java.awt.Color(255, 0, 0));
        lbTT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTT2.setText("0");
        lbTT2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTT1.setForeground(new java.awt.Color(255, 0, 0));
        lbTT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTT1.setText("0");
        lbTT1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Tổng tiền mặt đầu ca:");
        jLabel25.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtTongTien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTongTien.setForeground(new java.awt.Color(255, 0, 0));
        txtTongTien.setText("0");

        lbNhanCa.setBackground(new java.awt.Color(0, 153, 51));
        lbNhanCa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbNhanCa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNhanCa.setText("Nhận ca");
        lbNhanCa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbNhanCa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNhanCa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNhanCaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbMenhGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt500)
                            .addComponent(labelSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(txt200)
                            .addComponent(txt100)
                            .addComponent(txt50)
                            .addComponent(txt20)
                            .addComponent(txt10)
                            .addComponent(txt5)
                            .addComponent(txt2)
                            .addComponent(txt1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelThanhTien, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(lbTT500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTT200, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTT100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTT50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTT20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTT10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTT5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTT2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTongTien)))
            .addComponent(lbNhanCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbMenhGia, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(labelSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelThanhTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt500, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTT500, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt200, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTT200, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt100, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTT100, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt50, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTT50, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTT20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTT10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTT5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTT2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTT1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNhanCa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Khai Báo Tiền Đầu Ca");

        jLabel2.setText("Nhân viên:");

        lbTenNv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTenNv.setText("jLabel3");

        jLabel3.setText("Giờ hiện tại:");

        lbGioVaoCa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbGioVaoCa.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbGioVaoCa, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTenNv, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbTenNv))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbGioVaoCa))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelTongLayout = new javax.swing.GroupLayout(panelTong);
        panelTong.setLayout(panelTongLayout);
        panelTongLayout.setHorizontalGroup(
            panelTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTongLayout.createSequentialGroup()
                .addContainerGap(472, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(454, 454, 454))
        );
        panelTongLayout.setVerticalGroup(
            panelTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTongLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public int tinhTien(int menhGia, String soLuong, JLabel ThanhTien) {
        if (soLuong.matches("[a-z A-Z]+")) {
            JOptionPane.showMessageDialog(null, "Số lượng phải là số nguyên!");
            return 0;
        } else if (Integer.valueOf(soLuong) < 0) {
            JOptionPane.showMessageDialog(null, "Số lượng phải lớn hơn 0");
            return -1;
        } else {
            ThanhTien.setText(String.valueOf(Integer.valueOf(soLuong) * menhGia));
            return Integer.valueOf(soLuong) * menhGia;

        }
    }

    private void tongTIen() {
        txtTongTien.setText(String.valueOf(Integer.valueOf(lbTT500.getText()) + Integer.valueOf(lbTT200.getText()) + Integer.valueOf(lbTT100.getText()) + Integer.valueOf(lbTT50.getText()) + Integer.valueOf(lbTT20.getText()) + Integer.valueOf(lbTT10.getText()) + Integer.valueOf(lbTT5.getText()) + Integer.valueOf(lbTT2.getText()) + Integer.valueOf(lbTT1.getText())));

    }
    private void lbNhanCaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNhanCaMouseClicked
        if (txtTongTien.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Không để trống tổng tiền");
        } else if (!txtTongTien.getText().matches("\\d+") || Float.valueOf(txtTongTien.getText()) < 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đúng định dạng tiền hoặc tiền phải lớn hơn 0");
        } else {
            Acount acount = new Acount();
            acount.setId(qLAcount.getId());
            GiaoCa giaoCa = new GiaoCa(null, new MaRanDom().genMa("GiaoCa"), new Date(), null, qLAcount.getId(), null, Float.valueOf(txtTongTien.getText()), 0, 0, 0, 0, " ", 0, null, acount, 0, trangThaiGiaoCa.NHAN_CA);
            JOptionPane.showMessageDialog(null, giaoCaService.NhanCa(giaoCa));
            HomeController controller = new HomeController(pnTOng, qLAcount, new Date(), null);
            controller.setView(lableHome);
        }


    }//GEN-LAST:event_lbNhanCaMouseClicked

    private void txt500KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt500KeyTyped
        tinhTien(500000, txt500.getText() + evt.getKeyChar(), lbTT500);
        tongTIen();
    }//GEN-LAST:event_txt500KeyTyped

    private void txt200KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt200KeyTyped
        tinhTien(200000, txt200.getText() + evt.getKeyChar(), lbTT200);
        tongTIen();
    }//GEN-LAST:event_txt200KeyTyped

    private void txt100KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt100KeyTyped
        tinhTien(100000, txt100.getText() + evt.getKeyChar(), lbTT100);
        tongTIen();
    }//GEN-LAST:event_txt100KeyTyped

    private void txt50KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt50KeyTyped
        tinhTien(50000, txt50.getText() + evt.getKeyChar(), lbTT50);
        tongTIen();
    }//GEN-LAST:event_txt50KeyTyped

    private void txt20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt20KeyTyped
        tinhTien(20000, txt20.getText() + evt.getKeyChar(), lbTT20);
        tongTIen();
    }//GEN-LAST:event_txt20KeyTyped

    private void txt10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt10KeyTyped
        tinhTien(10000, txt10.getText() + evt.getKeyChar(), lbTT10);
        tongTIen();
    }//GEN-LAST:event_txt10KeyTyped

    private void txt5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt5KeyTyped
        tinhTien(5000, txt5.getText() + evt.getKeyChar(), lbTT5);
        tongTIen();
    }//GEN-LAST:event_txt5KeyTyped

    private void txt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2KeyTyped
        tinhTien(2000, txt2.getText() + evt.getKeyChar(), lbTT2);
        tongTIen();
    }//GEN-LAST:event_txt2KeyTyped

    private void txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyTyped
        tinhTien(1000, txt1.getText() + evt.getKeyChar(), lbTT1);
        tongTIen();
    }//GEN-LAST:event_txt1KeyTyped
    public Date gioNhanCa() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy - hh:mm:ss a");
        return new Timestamp(new Date().getTime());
    }

    public double tienBanDau() {
        return Double.valueOf(txtTongTien.getText());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelSoLuong;
    private javax.swing.JLabel labelThanhTien;
    private javax.swing.JLabel lbGioVaoCa;
    private javax.swing.JLabel lbMenhGia;
    private javax.swing.JLabel lbNhanCa;
    private javax.swing.JLabel lbTT1;
    private javax.swing.JLabel lbTT10;
    private javax.swing.JLabel lbTT100;
    private javax.swing.JLabel lbTT2;
    private javax.swing.JLabel lbTT20;
    private javax.swing.JLabel lbTT200;
    private javax.swing.JLabel lbTT5;
    private javax.swing.JLabel lbTT50;
    private javax.swing.JLabel lbTT500;
    private javax.swing.JLabel lbTenNv;
    private javax.swing.JPanel panelTong;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt100;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt20;
    private javax.swing.JTextField txt200;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt50;
    private javax.swing.JTextField txt500;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
